config/routes.rb
Rails.application.routes.draw do
  root "welcome#homepage"

  resources :books
  resources :stores

  mount Authoree::Engine, at: "/users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show; end
  def edit; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_url(@book), notice: "Book was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_url(@book), notice: "Book was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed"
  end

  private
  
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:author, :overview, :store_id)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  def index
    @stores = Store.all
  end

  def show; end
  def edit; end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to store_url(@store), notice: "Store was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @store.update(store_params)
      redirect_to store_url(@store), notice: "Store was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_url, notice: "Store was successfully destroyed"
  end

  private
  
  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:title)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="border rounded my-5 p-5">
  <div class="row">
    <div class="col-4">
      <p class="text-muted display-6">
        <%= book.author %>
      </p>
      <small class="text-info">
        <%= book.store.title %>
      </small>
    </div>

    <div class="col">
      <p class="text-success mb-4">
        <%= book.overview %>
      </p>
      <small>
        <span class="text-muted">Created</span> <%= time_ago_in_words book.created_at %> ago
      </small>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<div class="card shadow my-5 p-5">
  <%= simple_form_for(@book) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :author %>
      <%= f.input :overview %>
      <%= f.association :store %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-sm btn-outline-success mt-3' %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1 class="text-muted text-center">
  Editing book
</h1>

<%= render "form", book: @book %>

<br>

<div class="btn-group">
  <%= link_to "Show this book", @book, class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/books/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

<h1 class="text-muted text-center">
  Books
</h1>

<% @books.each do |book| %>
  <div class="card shadow my-5 p-5">
    <%= render book %>
    <p><%= link_to "Show this book", book, class: 'btn btn-sm btn-outline-primary mt-3' %></p>
  </div>
<% end %>

<%= link_to "New book", new_book_path, class: 'btn btn-sm btn-outline-success' %>

app/views/books/new.html.erb
<h1 class="text-center text-muted">
  New book
</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/books/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<%= render @book %>

<div class="btn-group">
  <%= link_to "Edit this book", edit_book_path(@book), class: 'btn btn-sm btn-outline-warning' %>
  <%= link_to "Back to books", books_path, class: 'btn btn-sm btn-outline-secondary' %>
  <%= button_to "Destroy this book", @book, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand mx-5" href="/">Engine</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= books_path %>">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= stores_path %>">Stores</a>
        </li>
        <li class="nav-item me-5">
          <a class="nav-link active" aria-current="page" href="<%= authoree.users_path %>">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_book_path %>">Create Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_store_path %>">Create Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= authoree.new_user_path %>">Create User</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Engine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="container">
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/stores/_form.html.erb
<div class="card shadow my-5 p-5">
  <%= simple_form_for(@store) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-sm btn-outline-success mt-3' %>
    </div>
  <% end %>
</div>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>" class="border rounded my-5 p-5">
  <div class="row">
    <div class="col-1">
      <p class="text-muted">
        Title
      </p>
      <p class="text-muted">
        Store Books
      </p>
    </div>

    <div class="col">
      <p class="text-success">
        <%= store.title %>
      </p>
      <p class="text-success">
        <% store.books.each do |book| %>
          <%= book.author %><br>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/stores/edit.html.erb
<h1 class="text-center text-muted">
  Editing store
</h1>

<%= render "form", store: @store %>

<br>

<div class="btn-group">
  <%= link_to "Show this store", @store, class: 'btn btn-sm btn-outline-primary' %>
  <%= link_to "Back to stores", stores_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/stores/index.html.erb
<p style="color: green">
  <%= notice %>
</p>

<h1 class="text-muted text-center">
  Stores
</h1>

<% @stores.each do |store| %>
  <div class="card shadow my-5 p-5">
    <%= render store %>
    <p><%= link_to "Show this store", store, class: 'btn btn-sm btn-outline-primary mt-3' %></p>
  </div>
<% end %>

<%= link_to "New book", new_store_path, class: 'btn btn-sm btn-outline-success' %>

app/views/stores/new.html.erb
<h1 class="text-center text-muted">
  New store
</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path, class: 'btn btn-sm btn-outline-secondary' %>
</div>

app/views/stores/show.html.erb
<p style="color: green">
  <%= notice %>
</p>

<%= render @store %>
<%= render partial: 'stores/books_list', locals: { books: @store.books } %>

<div class="btn-group">
  <%= link_to "Edit this store", edit_store_path(@store), class: 'btn btn-sm btn-outline-warning' %>
  <%= link_to "Back to stores", stores_path, class: 'btn btn-sm btn-outline-secondary' %>
  <%= button_to "Destroy this store", @store, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
</div>

app/views/welcome/homepage.html.erb
<p class="text-center text-success display-1">
  Welcome
</p>